# Generated by Django 6.0.5 on 2026-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Validação'), ('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='pendente', max_length=20),
        ),
    ]
