# Generated by Django 5.2.14 on 2026-05-27 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('emprestimo_aprovado', 'Empréstimo Aprovado'), ('emprestimo_rejeitado', 'Empréstimo Rejeitado'), ('fila_avanco', 'Avanço na Fila'), ('livro_disponivel', 'Livro Disponível'), ('prazo_proximo', 'Prazo Próximo'), ('emprestimo_atrasado', 'Empréstimo Atrasado'), ('devolucao_registrada', 'Devolução Registrada')], max_length=30)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
