# Generated by Django 6.0.5 on 2026-05-07 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliotecas', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='biblioteca',
            field=models.ForeignKey(blank=True, help_text='Obrigatório apenas para Bibliotecários. Usuários comuns podem alugar de várias bibliotecas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app_bibliotecas.biblioteca'),
        ),
    ]
